# Site settings
name: seoseokkyo
email: seoseokkyo@naver.com
url: "https://github.com/seoseokkyo"
description: "이력서와 포트폴리오"
author: "author"
title: "서석교 자기소개 페이지입니다."
permalink: pretty
baseurl: ""

# social
github:
  username: seoseokkyo
